name: Bug Report
description: Report a bug to help us improve hypr-opaque-media
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start hypr-opaque-media with configuration...
        2. Open window with class...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your hypr-opaque-media.json configuration file (remove any sensitive information)
      placeholder: Paste your config here...
      render: json
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant log output or error messages
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: hyprland-rule
    attributes:
      label: Hyprland Configuration
      description: Relevant parts of your hyprland.conf (especially windowrulev2 rules)
      placeholder: |
        windowrulev2 = opacity 1.0 1.0 override, tag:opaque
        # other relevant rules...
      render: shell
    validations:
      required: false

  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: Your Linux distribution and version
      placeholder: "e.g., Arch Linux, Ubuntu 22.04, Fedora 38"
    validations:
      required: true

  - type: input
    id: hyprland-version
    attributes:
      label: Hyprland Version
      description: Output of `hyprctl version`
      placeholder: "e.g., Hyprland 0.32.3 built from branch  at commit 0ba32c1c (props-v1)"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Output of `python --version`
      placeholder: "e.g., Python 3.11.6"
    validations:
      required: true

  - type: checkboxes
    id: environment-check
    attributes:
      label: Environment Check
      options:
        - label: I have watchdog installed (`pip show watchdog` shows package info)
        - label: I can run `hyprctl version` successfully
        - label: The issue persists with the latest version of hypr-opaque-media
        - label: I have checked existing issues and this is not a duplicate

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information...
    validations:
      required: false